services:
    exs_feeds_chaturbate.memcached:
        class: '\Memcached'
        calls:
            - ['addServer', ['%exs_feeds_chaturbate.memcached_host%', '%exs_feeds_chaturbate.memcached_port%']]

    exs_feeds_chaturbate.memcached.http_client:
        class: 'GuzzleHttp\Client'

    exs_feeds_chaturbate.feeds_reader:
        class: 'EXS\FeedsChaturbateBundle\Service\FeedsReader'
        arguments:
            - '@exs_feeds_chaturbate.memcached'
            - '@exs_feeds_chaturbate.memcached.http_client'
            - '%exs_feeds_chaturbate.cache_ttl%'
